# 1. Data 준비

> 서울

In [17]:
import os
import glob
import pandas as pd
import numpy as np

In [6]:
df_train_raw = pd.read_csv('./data/raw/train.csv')
df_test_raw = pd.read_csv('./data/raw/test.csv')

In [23]:
df_train_raw.city.unique()

array(['Sydney, Australia', 'Ubatuba, Brazil', 'Krakow, Poland', ...,
       'Zhuolan Township, Taiwan', 'Xiluo Township, Taiwan',
       'Navoiy, Uzbekistan'], dtype=object)

In [37]:
# df_train_raw[df_train_raw.city == 'Seoul, South Korea'].platform.value_counts()

In [138]:
df_s_1 = df_train_raw[df_train_raw.city == 'Seoul, South Korea'].reset_index(drop=True)
df_s_2 = df_test_raw[df_test_raw.city == 'Seoul, South Korea'].reset_index(drop=True)

In [139]:
df_s_1.to_csv('strain.csv',index=False)
df_s_2.to_csv('stest.csv',index=False)

In [ ]:
df_seoul_all = pd.concat([df_s_1, df_s_2]).reset_index(drop=True)

In [137]:
df_seoul_all['dt'].dt.date.value_counts().sort_index()

2018-11-01    5606
2018-11-02    3949
2018-11-03    4913
2018-11-04    7512
2018-11-05    6708
2018-11-06    4913
2018-11-07    2967
2018-11-08    3366
Name: dt, dtype: int64

In [128]:
df_seoul_all['dt'] = pd.to_datetime(df_seoul_all.timestamp, unit='s')

In [129]:
df_seoul_all.dt.dt.dayofweek.value_counts().sort_index()

In [26]:
# ?pd.set_option

In [25]:
pd.set_option("display.max_columns",0)

# 2. Data Prep

In [19]:
glob.glob("data/*.joblib")

['data/item_prices.joblib',
 'data/item_sort_by_rating_stats.joblib',
 'data/item_sort_by_distance_stats.joblib',
 'data/item_prices_rank.joblib',
 'data/price_pct_by_city.joblib',
 'data/item_pois.joblib',
 'data/price_pct_by_platform.joblib',
 'data/item_metadata_map.joblib',
 'data/item_sort_by_popularity_stats.joblib',
 'data/click_probs_by_index.joblib']

In [22]:
glob.glob("data/*.*")

['data/events_sorted_trans_all.csv',
 'data/item_prices.joblib',
 'data/events_sorted.csv',
 'data/download_data.sh',
 'data/item_sort_by_rating_stats.joblib',
 'data/item_metadata_dense.csv',
 'data/events_sorted_trans_002.csv',
 'data/events_sorted_trans_003.csv',
 'data/item_sort_by_distance_stats.joblib',
 'data/test.csv',
 'data/events_sorted_trans_001.csv',
 'data/price.csv',
 'data/events_sorted_trans_000.csv',
 'data/events_sorted_trans_004.csv',
 'data/events_sorted_trans_005.csv',
 'data/events_sorted_trans_007.csv',
 'data/item_prices_rank.joblib',
 'data/events_sorted_trans_006.csv',
 'data/price_pct_by_city.joblib',
 'data/scores.csv',
 'data/item_pois.joblib',
 'data/item_metadata.csv',
 'data/price_pct_by_platform.joblib',
 'data/comparison.csv',
 'data/train.csv',
 'data/item_metadata_map.joblib',
 'data/item_sort_by_popularity_stats.joblib',
 'data/click_probs_by_index.joblib']

In [28]:
df_es.action_type.unique()

array(['search for poi', 'filter selection', 'clickout item',
       'interaction item image', 'interaction item deals',
       'search for destination', 'interaction item info',
       'interaction item rating', 'search for item',
       'change of sort order'], dtype=object)

In [29]:
['search for poi', 'filter selection', 'clickout item',
       'interaction item image', 'interaction item deals',
       'search for destination', 'interaction item info',
       'interaction item rating', 'search for item',
       'change of sort order']

['search for poi',
 'filter selection',
 'clickout item',
 'interaction item image',
 'interaction item deals',
 'search for destination',
 'interaction item info',
 'interaction item rating',
 'search for item',
 'change of sort order']

In [30]:
import joblib

## 2.1 python convert_item_metadata_to_sets.py

In [32]:
dd = joblib.load("data/item_metadata_map.joblib")

In [35]:
# dd.keys()

In [43]:
# dd[5197174]

## 2.2 python extract_hotel_dense_features.py

In [40]:
df_im_dense = pd.read_csv("data/item_metadata_dense.csv")

In [41]:
df_im_dense

         item_id  n_properties  ...  pet_friendly  all_inclusive_(upon_inquiry)
0           5101            62  ...             0                             0
1           5416            46  ...             1                             0
2           5834            40  ...             0                             0
3           5910            41  ...             1                             0
4           6066            85  ...             1                             0
...          ...           ...  ...           ...                           ...
927137  11199990             1  ...             0                             0
927138  11236100             1  ...             0                             0
927139  11260526             1  ...             0                             0
927140  11263712             1  ...             0                             0
927141  11275316             1  ...             0                             0

[927142 rows x 13 columns]

## 2.3 python extract_item_prices.py

events_sorted.csv로 진짜 가격의 평균 집합

In [44]:
item_prices = joblib.load("data/item_prices.joblib")

In [46]:
item_prices[2733571]

111.18512658227849

In [102]:
item_prices[3553830]

41.71604938271605

## 2.4 python extract_item_prices_rank.py

In [47]:
item_prices_rank = joblib.load("data/item_prices_rank.joblib")

In [51]:
item_prices_rank

        item_id  price  ...  price_range  price_range_div
26128     34311     56  ...            0         1.000000
26726     34314     78  ...            0         1.000000
25856     34319     59  ...            0         1.000000
21663     34321     84  ...            0         1.000000
26946     34322     33  ...            0         1.000000
...         ...    ...  ...          ...              ...
26405  11185016     61  ...           28         1.528302
26406  11185016     81  ...           28         1.528302
25751  11254986     19  ...            2         1.105263
25752  11254986     20  ...            2         1.105263
25750  11254986     21  ...            2         1.105263

[27023 rows x 11 columns]

## 2.5 python generate_click_indices.py

In [52]:
click_probs_by_index = joblib.load("data/click_probs_by_index.joblib")

In [54]:
click_probs_by_index[(-22, 0)]

0.014705882352941176

In [56]:
click_probs_by_index[(0, 4)]

0.11627906976744186

뭔 의미인지는 모르겠음 / 다만 앞은 click offset / diff time으로 나옴

## 2.6 python assign_poi_to_items.py

In [57]:
item_pois = joblib.load("data/item_pois.joblib")

In [172]:
item_pois

defaultdict(set,
            {2733571: {'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Gangnam-gu',
              'Gimpo International Airport',
              'Gyeongbokgung',
              'Hongdae',
              'Hongik University',
              'Insadong',
              'Itaewon',
              'Jamsil Baseball Stadium',
              'Jamsil Sports Complex',
              'Jongno',
              'Konkuk University',
              'Lotte - Main',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea',
              'Sejong Center',
              'Seoul Station'},
             5197174: {'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Gangnam-gu',
              'Gyeongbok Palace Station Metro Gallery',
              'Hongdae',
              'Hongik University',
              'Jamsil Sports Complex',
              'Jung Gu',
              'Lotte - Main',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea',
              'Seoul Station'},
             5477718: {'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Gangnam-gu',
              'Gimpo International Airport',
              'Gyeongbok Palace Station Metro Gallery',
              'Gyeongbokgung',
              'Hongdae',
              'Hongik University',
              'Insadong',
              'Jung Gu',
              'Mokdong Stadium',
              'Myeong-dong',
              'Myeongdong',
              'Seoul Arts Center',
              'Seoul Station',
              'Seoul World Cup Stadium'},
             155374: {'COEX',
              'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Gangnam-gu',
              'Gimpo International Airport',
              'Gwanghwamun',
              'Gyeongbok Palace Station Metro Gallery',
              'Gyeongbokgung',
              'Hongdae',
              'Hongik University',
              'Insadong',
              'Itaewon',
              'Jamsil Baseball Stadium',
              'Jung Gu',
              'Konkuk University',
              'Lotte - Main',
              'Mapogu',
              'Mokdong Stadium',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea',
              'Seoul Station'},
             363101: {'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Gangnam-gu',
              'Gimpo International Airport',
              'Gwanghwamun',
              'Gyeongbok Palace Station Metro Gallery',
              'Gyeongbokgung',
              'Hongdae',
              'Hongik University',
              'Insadong',
              'Jongno',
              'Lotte - Main',
              'Mokdong Stadium',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea',
              'Seoul Station',
              'Yongsan station'},
             390361: {'Changdeokgung',
              'Deoksugung Palace Royal Guard-Changing Ceremony',
              'Gangnam-gu',
              'Gwanghwamun',
              'Gyeongbok Palace Station Metro Gallery',
              'Gyeongbokgung',
              'Hongdae',
              'Insadong',
              'Itaewon',
              'Jung Gu',
              'Mapogu',
              'Myeong-dong',
              'Myeongdong',
              'Seoul Station'},
             363071: {'COEX',
              'Deoksugung Palace Royal Guard-Changing Ceremony',
              'Gangnam-gu',
              'Gyeongbok Palace Station Metro Gallery',
              'Hongik University',
              'Jung Gu',
              'Lotte - Main',
              'Myeong-dong',
              'Myeongdong',
              'Seoul Station'},
             6625240: {'COEX',
              'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Dongdaemun Sijang',
              'Gangnam-gu',
              'Gimpo International Airport',
              'Gyeongbokgung',
              'Hongdae',
              'Hongik University',
              'Insadong',
              'Itaewon',
              'Jamsil Baseball Stadium',
              'Jongno',
              'Lotte - Main',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea',
              'Sejong Center',
              'Seoul Station',
              'Yongsan station'},
             386246: {'Gangnam-gu',
              'Gwanghwamun',
              'Gyeongbok Palace Station Metro Gallery',
              'Gyeongbokgung',
              'Hongik University',
              'Jung Gu',
              'Konkuk University',
              'Myeong-dong',
              'Myeongdong',
              'Seoul Station'},
             2802232: {'Changdeokgung',
              'Dongdaemun Market',
              'Gangnam-gu',
              'Gyeongbok Palace Station Metro Gallery',
              'Hongdae',
              'Hongik University',
              'Itaewon',
              'Myeong-dong',
              'Myeongdong',
              'Seoul Arts Center',
              'Seoul Station',
              'Yongsan station'},
             156083: {'COEX',
              'COEX Aquarium',
              'Changdeokgung',
              'Deoksugung Palace Royal Guard-Changing Ceremony',
              'Gangnam-gu',
              'Gwanghwamun',
              'Gyeongbok Palace Station Metro Gallery',
              'Gyeongbokgung',
              'Insadong',
              'Itaewon',
              'Jung Gu',
              'Mapogu',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea',
              'Seoul Station'},
             3501452: {'Changdeokgung',
              'Dongdaemun Market',
              'Gangnam-gu',
              'Gimpo International Airport',
              'Gwanghwamun',
              'Gyeongbok Palace Station Metro Gallery',
              'Hongdae',
              'Hongik University',
              'Insadong',
              'Itaewon',
              'Jamsil Sports Complex',
              'Jongno',
              'Jung Gu',
              'Lotte - Main',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea',
              'Sejong Center',
              'Seoul Station',
              'Yongsan station'},
             844336: {'COEX',
              'COEX Aquarium',
              'Changdeokgung',
              'Deoksugung Palace Royal Guard-Changing Ceremony',
              'Dongdaemun Market',
              'Gangnam-gu',
              'Gimpo International Airport',
              'Gwanghwamun',
              'Gyeongbok Palace Station Metro Gallery',
              'Gyeongbokgung',
              'Hongdae',
              'Hongik University',
              'Insadong',
              'Jung Gu',
              'Konkuk University',
              'Lotte - Main',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea',
              'Sejong Center',
              'Seoul Station'},
             2632672: {'COEX',
              'Dongdaemun Market',
              'Gangnam-gu',
              'Gyeongbok Palace Station Metro Gallery',
              'Hongdae',
              'Jamsil Sports Complex',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea',
              'Seoul Arts Center',
              'Seoul Station'},
             4773608: {'Deoksugung Palace Royal Guard-Changing Ceremony',
              'Dongdaemun Market',
              'Gangnam-gu',
              'Gimpo International Airport',
              'Gyeongbok Palace Station Metro Gallery',
              'Gyeongbokgung',
              'Hongdae',
              'Hongik University',
              'Insadong',
              'Itaewon',
              'Jongno',
              'Lotte - Main',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea',
              'Sejong Center',
              'Seoul Station',
              'Yongsan station'},
             4705542: {'Dongdaemun Market',
              'Gangnam-gu',
              'Gimpo International Airport',
              'Gyeongbokgung',
              'Hongdae',
              'Lotte - Main',
              'Myeong-dong',
              'Myeongdong'},
             2855981: {'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Dongdaemun Sijang',
              'Gangnam-gu',
              'Hongdae',
              'Hongik University',
              'Insadong',
              'Myeong-dong',
              'Myeongdong',
              'Sejong Center',
              'Seoul Station',
              'Yongsan station'},
             475286: {'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Gangnam-gu',
              'Gyeongbok Palace Station Metro Gallery',
              'Hongdae',
              'Insadong',
              'Myeong-dong',
              'Myeongdong',
              'Seoul Station'},
             363086: {'Changdeokgung',
              'Gangnam-gu',
              'Gyeongbok Palace Station Metro Gallery',
              'Gyeongbokgung',
              'Hongik University',
              'Jung Gu',
              'Mokdong Stadium',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea',
              'Seoul Arts Center'},
             5109850: {'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Gangnam-gu',
              'Gyeongbok Palace Station Metro Gallery',
              'Gyeongbokgung',
              'Hongdae',
              'Hongik University',
              'Insadong',
              'Jamsil Sports Complex',
              'Jung Gu',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea'},
             4774512: {'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Gangnam-gu',
              'Gimpo International Airport',
              'Gyeongbok Palace Station Metro Gallery',
              'Gyeongbokgung',
              'Hongdae',
              'Hongik University',
              'Insadong',
              'Jongno',
              'Jung Gu',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea',
              'Seoul Station'},
             3954788: {'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Dongdaemun Sijang',
              'Gangnam-gu',
              'Gyeongbok Palace Station Metro Gallery',
              'Gyeongbokgung',
              'Hongdae',
              'Hongik University',
              'Insadong',
              'Itaewon',
              'Jamsil Baseball Stadium',
              'Jamsil Sports Complex',
              'Lotte - Main',
              'Myeong-dong',
              'Myeongdong',
              'Seoul Station'},
             2199372: {'COEX',
              'Gangnam-gu',
              'Gyeongbokgung',
              'Hongdae',
              'Hongik University',
              'Myeong-dong',
              'Myeongdong'},
             363096: {'COEX Aquarium',
              'Changdeokgung',
              'Deoksugung Palace Royal Guard-Changing Ceremony',
              'Dongdaemun Market',
              'Gangnam-gu',
              'Gimpo International Airport',
              'Gwanghwamun',
              'Gyeongbok Palace Station Metro Gallery',
              'Hongdae',
              'Hongik University',
              'Insadong',
              'Lotte - Main',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea',
              'Seoul Station'},
             363046: {'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Gangnam-gu',
              'Gimpo International Airport',
              'Gyeongbok Palace Station Metro Gallery',
              'Hongdae',
              'Hongik University',
              'Insadong',
              'Itaewon',
              'Jamsil Baseball Stadium',
              'Jung Gu',
              'Myeong-dong',
              'Myeongdong',
              'Seoul Station'},
             4849224: {'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Dongdaemun Sijang',
              'Insadong',
              'Myeong-dong'},
             2736998: {'COEX',
              'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Dongdaemun Sijang',
              'Hongdae',
              'Hongik University',
              'Insadong',
              'Myeong-dong',
              'Myeongdong',
              'Seoul Station'},
             3126684: {'Deoksugung Palace Royal Guard-Changing Ceremony',
              'Dongdaemun Market',
              'Myeong-dong',
              'Myeongdong',
              'Seoul Station'},
             6267294: {'Dongdaemun Market',
              'Gangnam-gu',
              'Gyeongbokgung',
              'Hongdae',
              'Jamsil Baseball Stadium',
              'Jamsil Sports Complex',
              'Konkuk University',
              'Myeong-dong',
              'Myeongdong'},
             3142644: {'Dongdaemun Market', 'Myeongdong'},
             4602228: {'Dongdaemun Market', 'Seoul World Cup Stadium'},
             10606158: {'Dongdaemun Market', 'Myeong-dong', 'Myeongdong'},
             1891895: {'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Dongdaemun Sijang',
              'Hongdae',
              'Hongik University',
              'Insadong',
              'Jamsil Baseball Stadium',
              'Jamsil Sports Complex',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea',
              'Seoul Station',
              'Yongsan station'},
             155989: {'COEX',
              'Changdeokgung',
              'Dongdaemun Market',
              'Dongdaemun Sijang',
              'Gangnam-gu',
              'Gwanghwamun',
              'Gyeongbok Palace Station Metro Gallery',
              'Hongdae',
              'Itaewon',
              'Jamsil Sports Complex',
              'Mokdong Stadium',
              'Myeong-dong',
              'Myeongdong',
              'Seoul Station'},
             6893402: {'Changdeokgung',
              'Dongdaemun Market',
              'Dongdaemun Sijang',
              'Gangnam-gu',
              'Gyeongbok Palace Station Metro Gallery',
              'Hongdae',
              'Insadong',
              'Jamsil Sports Complex',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea',
              'Sejong Center',
              'Seoul Station',
              'Yongsan station'},
             6800422: {'Changdeokgung',
              'Dongdaemun Market',
              'Gangnam-gu',
              'Gimpo International Airport',
              'Gyeongbok Palace Station Metro Gallery',
              'Hongdae',
              'Insadong',
              'Itaewon',
              'Jamsil Baseball Stadium',
              'Jung Gu',
              'Lotte - Main',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea',
              'Seoul Station'},
             5760110: {'Dongdaemun Market', 'Myeongdong'},
             3145303: {'COEX',
              'COEX Aquarium',
              'Dongdaemun Market',
              'Hongdae',
              'Insadong',
              'Jamsil Sports Complex',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea',
              'Seoul Station'},
             4773978: {'Dongdaemun Market', 'Gangnam-gu', 'Myeong-dong'},
             4841728: {'COEX',
              'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Dongdaemun Sijang',
              'Gangnam-gu',
              'Hongdae',
              'Insadong',
              'Jamsil Baseball Stadium',
              'Konkuk University',
              'Myeong-dong',
              'Myeongdong'},
             2867638: {'Dongdaemun Market',
              'Dongdaemun Sijang',
              'Gangnam-gu',
              'Hongdae',
              'Konkuk University',
              'Myeongdong',
              'National Theater of Korea'},
             475131: {'COEX',
              'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Dongdaemun Sijang',
              'Gangnam-gu',
              'Gimpo International Airport',
              'Gyeongbok Palace Station Metro Gallery',
              'Gyeongbokgung',
              'Hongdae',
              'Hongik University',
              'Insadong',
              'Itaewon',
              'Jamsil Baseball Stadium',
              'Jongno',
              'Jung Gu',
              'Myeong-dong',
              'Myeongdong',
              'Sejong Center',
              'Seoul Station',
              'Yongsan station'},
             797516: {'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Hongdae',
              'Hongik University',
              'Mokdong Stadium',
              'Myeong-dong',
              'Myeongdong',
              'Seoul Station'},
             5677278: {'Changdeokgung',
              'Dongdaemun Market',
              'Dongdaemun Sijang',
              'Hongdae',
              'Jamsil Sports Complex',
              'Jung Gu',
              'Konkuk University',
              'Mokdong Stadium',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea'},
             2611356: {'Dongdaemun Market', 'Myeong-dong'},
             4024148: {'Dongdaemun Market', 'Hongdae', 'Myeongdong'},
             7016734: {'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Hongdae',
              'Insadong',
              'Myeong-dong',
              'Myeongdong',
              'Seoul Station'},
             385916: {'Dongdaemun Market',
              'Dongdaemun Sijang',
              'Gangnam-gu',
              'Hongdae',
              'Itaewon',
              'Myeong-dong',
              'Myeongdong'},
             5950608: {'Dongdaemun Market'},
             155465: {'COEX',
              'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Dongdaemun Sijang',
              'Gangnam-gu',
              'Gwanghwamun',
              'Gyeongbok Palace Station Metro Gallery',
              'Hongdae',
              'Hongik University',
              'Insadong',
              'Jongno',
              'Jung Gu',
              'Lotte - Main',
              'Mapogu',
              'Myeong-dong',
              'Myeongdong',
              'National Theater of Korea',
              'Sejong Center',
              'Seoul Station',
              'Yongsan station'},
             157081: {'COEX Aquarium',
              'Changdeokgung',
              'Dongdaemun Market',
              'Gangnam-gu',
              'Gimpo International Airport',
              'Gwanghwamun',
              'Gyeongbok Palace Station Metro Gallery',
              'Hongik University',
              'Insadong',
              'Jamsil Baseball Stadium',
              'Jongno',
              'Jung Gu',
              'Lotte - Main',
              'Myeong-dong',
              'Myeongdong'},
             6340028: {'Dongdaemun Market',
              'Gangnam-gu',
              'Gwanghwamun',
              'Gyeongbok Palace Station Metro Gallery',

## 2.7 python extract_city_prices_percentiles.py

도시별 / 플랫폼별 가격별 백분위

In [60]:
price_pct_by_city = joblib.load("data/price_pct_by_city.joblib")
price_pct_by_platform = joblib.load("data/price_pct_by_platform.joblib")

In [62]:
price_pct_by_city[('Seoul, South Korea', 149)]

0.7659513754137656

In [64]:
prices = {}
for pf, price in price_pct_by_platform.keys():
    if pf == "KR":
        prices[price] = price_pct_by_platform[(pf, price)]

In [66]:
prices[120]

0.5576804441702653

## 2.8 python extract_item_rating.py

item_metadata_dense.csv
events_sorted.csv

In [68]:
item_ratings = [
    joblib.load(fn)
    for fn in glob.glob("data/item_sort_by_*_stats.joblib")
]

In [69]:
glob.glob("data/item_sort_by_*_stats.joblib")

['data/item_sort_by_rating_stats.joblib',
 'data/item_sort_by_distance_stats.joblib',
 'data/item_sort_by_popularity_stats.joblib']

In [71]:
item_ratings[0][2733571]

0.625

In [72]:
item_ratings[1][2733571]

0.6206896551724138

In [73]:
item_ratings[2][2733571]

0.6126126126126126

In [75]:
# item_ratings[0]

앞에 나온 횟수 / (앞에 나온 횟수 / 뒤에 나온 횟수)
```python
good_item[item_id] / (good_item[item_id] + bad_item[item_id])
```

# 3. Event_Sorted

In [4]:
df_im = pd.read_csv(os.path.join('data','item_metadata.csv'))
df_es = pd.read_csv(os.path.join('data','events_sorted.csv'))

In [5]:
df_im

         item_id                                         properties
0           5101  Satellite TV|Golf Course|Airport Shuttle|Cosme...
1           5416  Satellite TV|Cosmetic Mirror|Safe (Hotel)|Tele...
2           5834  Satellite TV|Cosmetic Mirror|Safe (Hotel)|Tele...
3           5910  Satellite TV|Sailing|Cosmetic Mirror|Telephone...
4           6066  Satellite TV|Sailing|Diving|Cosmetic Mirror|Sa...
...          ...                                                ...
927137  11199990                                  House / Apartment
927138  11236100                                  House / Apartment
927139  11260526                                  House / Apartment
927140  11263712                                  House / Apartment
927141  11275316                                              Hotel

[927142 rows x 2 columns]

In [141]:
df_es.is_test.value_counts()

0    39495
1      439
Name: is_test, dtype: int64

In [142]:
df_es.is_val.value_counts()

0    39684
1      250
Name: is_val, dtype: int64

In [86]:
df_es_ci = df_es[df_es.action_type == "clickout item"]

In [90]:
df_es_ci["imp_list"] = df_es_ci.impressions.map(lambda x: x.split("|"))

/Users/josang-yeon/tobigs/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [93]:
df_es_ci["imp_list"].map(lambda x: len(x)).sum()

109744

In [96]:
df_es_ci["imp_list"][39932]

['3553830',
 '4717538',
 '2380206',
 '2751236',
 '7675878',
 '2516656',
 '9267246',
 '2815425',
 '2079536',
 '10273386',
 '6478954',
 '7165930',
 '9564676',
 '9858786',
 '9365228']

In [154]:
df_es

            user_id     session_id   timestamp  ...  clickout_max_step          dt is_val
0      6B86JDD3UW7A  447ef5a11b6fc  1541030611  ...                  1  2018-11-01      0
1      6B86JDD3UW7A  447ef5a11b6fc  1541030675  ...                  1  2018-11-01      0
2      6B86JDD3UW7A  447ef5a11b6fc  1541030775  ...                  1  2018-11-01      0
3      LAYU76NFE98T  61208de881b0e  1541030959  ...                  2  2018-11-01      0
4      LAYU76NFE98T  61208de881b0e  1541030959  ...                  2  2018-11-01      0
...             ...            ...         ...  ...                ...         ...    ...
39929  0Z4IB9MP6ZFX  7717feba41db7  1541719852  ...                  1  2018-11-08      0
39930  0Z4IB9MP6ZFX  7717feba41db7  1541719862  ...                  1  2018-11-08      0
39931  0Z4IB9MP6ZFX  7717feba41db7  1541719871  ...                  1  2018-11-08      0
39932  XHK8346FKDN9  afb0ecf8b6773  1541720331  ...                  1  2018-11-08      0
39933  M9KCCP0T97FW  9356a7ae1f553  1541721077  ...                  1  2018-11-08      0

[39934 rows x 21 columns]

# 3. Cpp

## 3.1 price

In [106]:
df_prices = pd.read_csv("data/price.csv")

In [107]:
df_prices

        pure_price  mean_price  ...  max_prev_3_vs_item_price  mean_prev_3_vs_item_price
0              107       11140  ...                       100                        100
1              162       11140  ...                       100                         83
2               86       11140  ...                       188                        137
3              171       11140  ...                       100                         76
4              155       11140  ...                       110                         92
...            ...         ...  ...                       ...                        ...
109739          16        1646  ...                       112                        104
109740          17        1646  ...                       105                         97
109741          18        1646  ...                       100                         91
109742          13        1646  ...                       138                        123
109743          19        1646  ...                       100                         88

[109744 rows x 36 columns]

In [81]:
"max_after_price,max_before_price,max_vs_item_price,mean_price,mean_after_vs_item_price,mean_before_vs_item_price,mean_first_3_vs_item_price,mean_prev_3_vs_item_price,min_price,min_after_price,min_before_vs_item_price,prev_1_vs_item_price,prev_2_vs_item_price,pure_price,rank_norm_price,rank_norm_after_price".split(",")

['max_after_price',
 'max_before_price',
 'max_vs_item_price',
 'mean_price',
 'mean_after_vs_item_price',
 'mean_before_vs_item_price',
 'mean_first_3_vs_item_price',
 'mean_prev_3_vs_item_price',
 'min_price',
 'min_after_price',
 'min_before_vs_item_price',
 'prev_1_vs_item_price',
 'prev_2_vs_item_price',
 'pure_price',
 'rank_norm_price',
 'rank_norm_after_price']

In [83]:
len([19,1646,86,10,52,19,100,12,80,1646,86,10,52,19,100,1900,100,19,100,19,100,12,80,0,0,52,100,78,111,105,146,100,100,68,100,88])

36

In [97]:
len(["pure",
       "mean",
       "mean_vs_item",
       "min",
       "min_vs_item",
       "max",
       "max_vs_item",
       "rank",
       "rank_norm",
       "mean_before",
       "mean_before_vs_item",
       "min_before",
       "min_before_vs_item",
       "max_before",
       "max_before_vs_item",
       "mean_after",
       "mean_after_vs_item",
       "min_after",
       "min_after_vs_item",
       "max_after",
       "max_after_vs_item",
       "rank_before",
       "rank_norm_before",
       "rank_after",
       "rank_norm_after",
       "min_first_3_vs_item",
       "max_first_3_vs_item",
       "mean_first_3_vs_item",
       "prev_3_vs_item",
       "prev_2_vs_item",
       "prev_1_vs_item",
       "next_1_vs_item",
       "next_2_vs_item",
       "min_prev_3_vs_item",
       "max_prev_3_vs_item",
       "mean_prev_3_vs_item"])

36

## 3.2 Scores

In [108]:
df_scores = pd.read_csv("data/scores.csv")

In [109]:
df_scores.tail(5)

                                       clickout_counter  ...                                 identifier_counter
4434  10|0|3|2|1|1|10|1|3|0|3|3|1|0|2|4|1|9|6|12|4|2...  ...  6562554|4385526|8198340|9267246|4217920|715497...
4435  12|2|4|0|0|12|1|3|1|0|3|0|0|3|1|2|3|10|2|4|4|2...  ...  1716963|2109322|6994054|3793458|4534962|283610...
4436  45|34|87|56|87|38|18|28|17|33|44|49|11|24|20|1...  ...  844336|385916|363046|2733571|3501452|475131|47...
4437  9|0|18|3|1|6|2|2|6|2|3|1|6|2|0|0|0|0|0|0|0|0|1...  ...  1494251|6627182|2292524|4531854|6477586|238020...
4438                     11|4|6|1|0|7|2|2|0|5|2|0|0|0|5  ...  3553830|4717538|2380206|2751236|7675878|251665...

[5 rows x 9 columns]

In [110]:
df_scores.columns

Index(['clickout_counter', 'impression_counter', 'interaction_counter',
       'mean_rank_counter', 'top_7_impression_counter',
       'interaction_counter_vs_impression_counter',
       'clickout_counter_vs_impression_counter',
       'clickout_counter_vs_interaction_counter', 'identifier_counter'],
      dtype='object')

## 3.3 Comparison

In [114]:
df_comp = pd.read_csv("data/comparison.csv")

In [115]:
df_comp.columns

Index(['clickout_counter_pure', 'clickout_counter_mean',
       'clickout_counter_mean_vs_item', 'clickout_counter_min',
       'clickout_counter_min_vs_item', 'clickout_counter_max',
       'clickout_counter_max_vs_item', 'clickout_counter_rank',
       'clickout_counter_rank_norm', 'clickout_counter_mean_before',
       ...
       'top_7_impression_counter_max_first_3_vs_item',
       'top_7_impression_counter_mean_first_3_vs_item',
       'top_7_impression_counter_prev_3_vs_item',
       'top_7_impression_counter_prev_2_vs_item',
       'top_7_impression_counter_prev_1_vs_item',
       'top_7_impression_counter_next_1_vs_item',
       'top_7_impression_counter_next_2_vs_item',
       'top_7_impression_counter_min_prev_3_vs_item',
       'top_7_impression_counter_max_prev_3_vs_item',
       'top_7_impression_counter_mean_prev_3_vs_item'],
      dtype='object', length=324)

In [116]:
df_comp

        clickout_counter_pure  ...  top_7_impression_counter_mean_prev_3_vs_item
0                           0  ...                                         10000
1                           0  ...                                         10000
2                           0  ...                                         10000
3                           0  ...                                         10000
4                           0  ...                                         10000
...                       ...  ...                                           ...
109739                      2  ...                                           139
109740                      0  ...                                           412
109741                      0  ...                                           258
109742                      0  ...                                           120
109743                      0  ...                                            27

[109744 rows x 324 columns]

In [ ]:
["clickout_counter_vs_interaction_counter_mean",
"mean_rank_counter_mean",
"identifier_counter_min_after",
"interaction_counter_pure",
"identifier_counter_max_after",
"identifier_counter_mean_before_vs_item",
"identifier_counter_prev_2_vs_item",
"interaction_counter_max_vs_item",
"interaction_counter_mean",
"mean_rank_counter_mean_after_vs_item",
"mean_rank_counter_rank_norm_after",
"mean_rank_counter_max_vs_item",
"mean_rank_counter_min",
"impression_counter_prev_1_vs_item",
"impression_counter_mean_before_vs_item",
"clickout_counter_vs_impression_counter_max_after",
"clickout_counter_vs_impression_counter_max_before",
"identifier_counter_rank_norm_after",
"impression_counter_rank_norm",
"impression_counter_mean_prev_3_vs_item",
"clickout_counter_vs_interaction_counter_pure",
"impression_counter_min_before_vs_item",
"top_7_impression_counter_mean_first_3_vs_item",
"interaction_counter_vs_impression_counter_max_before"]

In [112]:
df_selected = pd.read_csv("data/features/comp_v0_selected.csv")

In [117]:
df_selected.columns

Index(['clickout_counter_vs_interaction_counter_mean',
       'mean_rank_counter_mean', 'identifier_counter_min_after',
       'interaction_counter_pure', 'identifier_counter_max_after',
       'identifier_counter_mean_before_vs_item',
       'identifier_counter_prev_2_vs_item', 'interaction_counter_max_vs_item',
       'interaction_counter_mean', 'mean_rank_counter_mean_after_vs_item',
       'mean_rank_counter_rank_norm_after', 'mean_rank_counter_max_vs_item',
       'mean_rank_counter_min', 'impression_counter_prev_1_vs_item',
       'impression_counter_mean_before_vs_item',
       'clickout_counter_vs_impression_counter_max_after',
       'clickout_counter_vs_impression_counter_max_before',
       'identifier_counter_rank_norm_after', 'impression_counter_rank_norm',
       'impression_counter_mean_prev_3_vs_item',
       'clickout_counter_vs_interaction_counter_pure',
       'impression_counter_min_before_vs_item',
       'top_7_impression_counter_mean_first_3_vs_item',
       'interaction_counter_vs_impression_counter_max_before'],
      dtype='object')

In [13]:
import sys
sys.path.append('/Users/josang-yeon/2020/tobigs/tobigs_reco_conf/recsys2019/src')
from recsys.vectorizers import make_vectorizer_1, VectorizeChunks

## 4. Generate (피쳐 생성)

In [ ]:
"src/recsys/data_generator/accumulators.py"

In [119]:
df_trans_01 = pd.read_csv("data/events_sorted_trans_001.csv")

In [122]:
df_trans_01.columns.shape

(17,)

In [123]:
17*8

136

In [171]:
df_es

            user_id     session_id  ...          dt  is_val
0      6B86JDD3UW7A  447ef5a11b6fc  ...  2018-11-01       0
1      6B86JDD3UW7A  447ef5a11b6fc  ...  2018-11-01       0
2      6B86JDD3UW7A  447ef5a11b6fc  ...  2018-11-01       0
3      LAYU76NFE98T  61208de881b0e  ...  2018-11-01       0
4      LAYU76NFE98T  61208de881b0e  ...  2018-11-01       0
...             ...            ...  ...         ...     ...
39929  0Z4IB9MP6ZFX  7717feba41db7  ...  2018-11-08       0
39930  0Z4IB9MP6ZFX  7717feba41db7  ...  2018-11-08       0
39931  0Z4IB9MP6ZFX  7717feba41db7  ...  2018-11-08       0
39932  XHK8346FKDN9  afb0ecf8b6773  ...  2018-11-08       0
39933  M9KCCP0T97FW  9356a7ae1f553  ...  2018-11-08       0

[39934 rows x 21 columns]

In [131]:
df_trans_01

        identical_impressions_item_clicks2  ...  is_item_within_avg_span_2s
0                                        0  ...                          -1
1                                        0  ...                          -1
2                                        0  ...                          -1
3                                        0  ...                          -1
4                                        0  ...                          -1
...                                    ...  ...                         ...
109739                                   0  ...                          -1
109740                                   0  ...                          -1
109741                                   0  ...                          -1
109742                                   0  ...                          -1
109743                                   0  ...                          -1

[109744 rows x 17 columns]

In [124]:
df_t_0 = pd.read_csv("data/proc/raw_csv/01_train_0000.csv")

In [129]:
df_t_0[["clickout_counter_vs_interaction_counter_mean",
"mean_rank_counter_mean",
"identifier_counter_min_after",
"interaction_counter_pure",
"identifier_counter_max_after",
"identifier_counter_mean_before_vs_item",
"identifier_counter_prev_2_vs_item",
"interaction_counter_max_vs_item",
"interaction_counter_mean",
"mean_rank_counter_mean_after_vs_item",
"mean_rank_counter_rank_norm_after",
"mean_rank_counter_max_vs_item",
"mean_rank_counter_min",
"impression_counter_prev_1_vs_item",
"impression_counter_mean_before_vs_item",
"clickout_counter_vs_impression_counter_max_after",
"clickout_counter_vs_impression_counter_max_before",
"identifier_counter_rank_norm_after",
"impression_counter_rank_norm",
"impression_counter_mean_prev_3_vs_item",
"clickout_counter_vs_interaction_counter_pure",
"impression_counter_min_before_vs_item",
"top_7_impression_counter_mean_first_3_vs_item",
"interaction_counter_vs_impression_counter_max_before"]]

      clickout_counter_vs_interaction_counter_mean  ...  interaction_counter_vs_impression_counter_max_before
0                                            10000  ...                                                 20
1                                            10000  ...                                                100
2                                            10000  ...                                                  1
3                                            10000  ...                                                  1
4                                            10000  ...                                                  1
...                                            ...  ...                                                ...
3654                                           151  ...                                                 89
3655                                            45  ...                                                 73
3656                                            82  ...                                                 84
3657                                           166  ...                                                 87
3658                                           194  ...                                                 87

[3659 rows x 24 columns]

In [178]:
cpp_cols = ["clickout_counter_vs_interaction_counter_mean",
"mean_rank_counter_mean",
"identifier_counter_min_after",
"interaction_counter_pure",
"identifier_counter_max_after",
"identifier_counter_mean_before_vs_item",
"identifier_counter_prev_2_vs_item",
"interaction_counter_max_vs_item",
"interaction_counter_mean",
"mean_rank_counter_mean_after_vs_item",
"mean_rank_counter_rank_norm_after",
"mean_rank_counter_max_vs_item",
"mean_rank_counter_min",
"impression_counter_prev_1_vs_item",
"impression_counter_mean_before_vs_item",
"clickout_counter_vs_impression_counter_max_after",
"clickout_counter_vs_impression_counter_max_before",
"identifier_counter_rank_norm_after",
"impression_counter_rank_norm",
"impression_counter_mean_prev_3_vs_item",
"clickout_counter_vs_interaction_counter_pure",
"impression_counter_min_before_vs_item",
"top_7_impression_counter_mean_first_3_vs_item",
"interaction_counter_vs_impression_counter_max_before"]

In [180]:
numerical_features_info = [
    ("avg_price_similarity", True),
    ("avg_price_similarity_to_interacted_items", True),
    ("avg_price_similarity_to_interacted_session_items", True),
    ("avg_similarity_to_interacted_items", True),
    ("avg_similarity_to_interacted_session_items", True),
    ("clicked_before", False),
    # ItemCTR
    ("clickout_item_clicks", False),
    ("clickout_item_impressions", False),
    ("clickout_item_ctr", False),
    ("clickout_item_ctr_corr", False),
    ("clickout_item_clicks_by_platform_device", False),
    ("clickout_item_impressions_by_platform_device", False),
    ("clickout_item_ctr_by_platform_device", False),
    ("clickout_item_ctr_corr_by_platform_device", False),
    ("clickout_item_clicks_by_platform", False),
    ("clickout_item_impressions_by_platform", False),
    ("clickout_item_ctr_by_platform", False),
    ("clickout_item_ctr_corr_by_platform", False),
    ("clickout_item_clicks_by_device", False),
    ("clickout_item_impressions_by_device", False),
    ("clickout_item_ctr_by_device", False),
    ("clickout_item_ctr_corr_by_device", False),
    ("interact_item_clicks", False),
    ("interact_item_impressions", False),
    ("interact_item_ctr", False),
    ("interact_item_clicks_by_platform_device", False),
    ("interact_item_impressions_by_platform_device", False),
    ("interact_item_ctr_by_platform_device", False),
    ("interact_item_clicks_by_platform", False),
    ("interact_item_impressions_by_platform", False),
    ("interact_item_ctr_by_platform", False),
    ("interact_item_clicks_by_device", False),
    ("interact_item_impressions_by_device", False),
    ("interact_item_ctr_by_device", False),
    ("clickout_user_item_clicks", True),
    ("user_item_ctr", True),
    ("clickout_item_item_last_timestamp", False),
    ("clickout_item_platform_clicks", True),
    ("clickout_prob_time_position_offset", True),
    ("country_eq_platform", False),
    ("fake_last_index_1", False),
    ("fake_last_index_2", False),
    ("fake_last_index_3", False),
    ("fake_last_index_4", False),
    ("fake_last_index_5", False),
    ("fake_last_index_diff_1", False),
    ("fake_last_index_diff_2", False),
    ("fake_last_index_diff_3", False),
    ("fake_last_index_diff_4", False),
    ("fake_last_index_diff_5", False),
    ("fake_n_consecutive_clicks", True),
    ("filter_selection_count", False),
    ("hour", False),
    ("identical_impressions_item_clicks", True),
    ("identical_impressions_item_clicks2", False),
    ("interaction_deal_freq", True),
    ("interaction_img_diff_ts", False),
    ("interaction_img_freq", True),
    ("interaction_info_freq", True),
    ("interaction_item_image_item_last_timestamp", False),
    ("interaction_rating_freq", True),
    ("is_impression_the_same", False),
    ("item_id", True),
    ("item_similarity_to_last_clicked_item", True),
    ("last_index_1", False),
    ("last_index_2", False),
    ("last_index_3", False),
    ("last_index_4", False),
    ("last_index_5", False),
    ("last_index_diff_1", False),
    ("last_index_diff_2", False),
    ("last_index_diff_3", False),
    ("last_index_diff_4", False),
    ("last_index_diff_5", False),
    ("last_ts_diff_1", False),
    ("last_ts_diff_2", False),
    ("last_ts_diff_3", False),
    ("last_ts_diff_4", False),
    ("last_ts_diff_5", False),
    ("last_item_fake_index", False),
    ("last_item_index", False),
    ("last_poi_item_clicks", True),
    ("last_poi_item_ctr", True),
    ("last_poi_item_impressions", True),
    ("last_price_diff", True),
    ("n_consecutive_clicks", True),
    ("n_properties", True),
    ("num_pois", True),
    ("poi_avg_similarity_to_interacted_items", True),
    ("poi_item_similarity_to_last_clicked_item", True),
    ("price", True),
    ("price_vs_max_price", False),
    ("price_vs_mean_price", False),
    ("rank", False),
    ("rating", True),
    ("stars", True),
    ("user_fake_rank_preference", True),
    ("user_impression_rank_preference", True),
    ("user_rank_preference", True),
    ("user_session_rank_preference", True),
    ("was_interaction_deal", False),
    ("was_interaction_img", False),
    ("was_interaction_info", False),
    ("was_interaction_rating", False),
    ("was_item_searched", False),
    ("price_pct_by_city", True),
    ("price_pct_by_platform", True),
    ("session_start_ts", False),
    ("user_start_ts", False),
    ("session_count", False),
    ("step", False),
    ("clickout_step_rev", False),
    ("clickout_step", False),
    ("clickout_max_step", False),
    ("clickout_item_clicks_rank_weighted", False),
    ("clickout_item_impressions_rank_weighted", False),
    ("clickout_item_ctr_rank_weighted", False),
    ("item_clicks_when_last", False),
    ("item_impressions_when_last", False),
    ("item_ctr_when_last", False),
    ("item_average_seq_pos", False),
    ("similar_users_item_interaction", True),
    ("most_similar_item_interaction", True),
    ("datetime_hour", False),
    ("datetime_minute", False),
    ("datetime_local_hour", False),
    ("datetime_local_minute", False),
    ("price_rank_asc", True),
    ("price_rank_desc", True),
    ("price_rank_asc_pct", True),
    ("min_price", True),
    ("max_price", True),
    ("count_price", True),
    ("price_range", True),
    ("price_range_div", True),
    ("price_relative_to_min", True),
    ("item_stats_distance", True),
    ("item_stats_rating", True),
    ("item_stats_popularity", True),
    ("click_sequence_min", False),
    ("click_sequence_max", False),
    ("click_sequence_min_norm", False),
    ("click_sequence_max_norm", False),
    ("click_sequence_len", False),
    ("click_sequence_sd", False),
    ("click_sequence_mean", False),
    ("click_sequence_mean_norm", False),
    ("click_sequence_gzip_len", False),
    ("click_sequence_entropy", False),
    ("fake_click_sequence_min", False),
    ("fake_click_sequence_max", False),
    ("fake_click_sequence_min_norm", False),
    ("fake_click_sequence_max_norm", False),
    ("fake_click_sequence_len", False),
    ("fake_click_sequence_sd", False),
    ("fake_click_sequence_mean", False),
    ("fake_click_sequence_mean_norm", False),
    ("fake_click_sequence_gzip_len", False),
    ("fake_click_sequence_entropy", False),
    # cpp features
#     ("clickout_counter_vs_interaction_counter_mean", False),
#     ("mean_rank_counter_mean", False),
#     ("identifier_counter_min_after", False),
#     ("interaction_counter_pure", False),
#     ("identifier_counter_max_after", False),
#     ("identifier_counter_mean_before_vs_item", False),
#     ("identifier_counter_prev_2_vs_item", False),
#     ("interaction_counter_max_vs_item", False),
#     ("interaction_counter_mean", False),
#     ("mean_rank_counter_mean_after_vs_item", False),
#     ("mean_rank_counter_rank_norm_after", False),
#     ("mean_rank_counter_max_vs_item", False),
#     ("mean_rank_counter_min", False),
#     ("impression_counter_prev_1_vs_item", False),
#     ("impression_counter_mean_before_vs_item", False),
#     ("clickout_counter_vs_impression_counter_max_after", False),
#     ("clickout_counter_vs_impression_counter_max_before", False),
#     ("identifier_counter_rank_norm_after", False),
#     ("impression_counter_rank_norm", False),
#     ("impression_counter_mean_prev_3_vs_item", False),
#     ("clickout_counter_vs_interaction_counter_pure", False),
#     ("impression_counter_min_before_vs_item", False),
#     ("top_7_impression_counter_mean_first_3_vs_item", False),
#     ("interaction_counter_vs_impression_counter_max_before", False),
    ("price_rem", False),
    ("are_price_sorted", False),
    ("are_price_sorted_rev", False),
    ("prices_sorted_until", False),
    ("prices_sorted_until_current_rank", False),
    ("wrong_price_sorting", False),
    ("clickout_uniq_interactions", False),
    ("clickout_item_uniq_prob", True),
    ("interact_uniq_interactions", False),
    ("interact_item_uniq_prob", True),
    ("pairwise_1_ctr_left_won", False),
    ("pairwise_1_ctr_right_won", False),
    ("pairwise_1_ctr_draw", True),
    ("pairwise_1_rel", False),
    ("pairwise_2_ctr_left_won", False),
    ("pairwise_2_ctr_right_won", False),
    ("pairwise_2_ctr_draw", False),
    ("pairwise_2_rel", False),
    ("average_fresh_rank", True),
    ("average_fresh_rank_rel", False),
    ("last_item_timestamp", True),
    ("last_item_click_same_user", False),
    ("item_was_in_prv_clickout", False),
    ("item_clickouts_intersection", False),
    ("rank_based_ctr", False),
    ("item_last_rank", False),
    ("item_avg_rank", False),
    ("user_item_avg_attention", False),
    ("is_item_within_avg_span", False),
    ("is_item_within_avg_span_2s", False),
    ("predicted_ind_minmax_by_user_id", False),
    ("predicted_ind_rel_minmax_by_user_id", False),
    ("ind_per_ts_minmax_by_user_id", False),
    ("predicted_ind_lr_by_user_id", False),
    ("predicted_ind_rel_lr_by_user_id", False),
    ("predicted_ind_rel_minmax_by_session_id", False),
    ("ind_per_ts_minmax_by_session_id", False),
]

In [187]:
num_cols = {col:True for col, _ in [("clickout_counter_vs_interaction_counter_mean", False),
    ("mean_rank_counter_mean", False),
    ("identifier_counter_min_after", False),
    ("interaction_counter_pure", False),
    ("identifier_counter_max_after", False),
    ("identifier_counter_mean_before_vs_item", False),
    ("identifier_counter_prev_2_vs_item", False),
    ("interaction_counter_max_vs_item", False),
    ("interaction_counter_mean", False),
    ("mean_rank_counter_mean_after_vs_item", False),
    ("mean_rank_counter_rank_norm_after", False),
    ("mean_rank_counter_max_vs_item", False),
    ("mean_rank_counter_min", False),
    ("impression_counter_prev_1_vs_item", False),
    ("impression_counter_mean_before_vs_item", False),
    ("clickout_counter_vs_impression_counter_max_after", False),
    ("clickout_counter_vs_impression_counter_max_before", False),
    ("identifier_counter_rank_norm_after", False),
    ("impression_counter_rank_norm", False),
    ("impression_counter_mean_prev_3_vs_item", False),
    ("clickout_counter_vs_interaction_counter_pure", False),
    ("impression_counter_min_before_vs_item", False),
    ("top_7_impression_counter_mean_first_3_vs_item", False),
    ("interaction_counter_vs_impression_counter_max_before", False),]}

In [189]:
len(num_cols.keys())

24

In [190]:
len(cpp_cols)

24

In [188]:
for cpp_col in cpp_cols:
    if not num_cols.get(cpp_col):
        print(cpp_col)
#     print(cpp_col)

In [132]:
df_t_0[[
                "user_id",
                "session_id",
                "platform",
                "device",
                "city",
                "timestamp",
                "step",
                "clickout_id",
                "item_id",
                "src",
                "is_test",
                "is_val",
                "was_clicked",
            ]]

           user_id     session_id platform  ... is_test is_val  was_clicked
0     68NZJ2NODJYM  c24ec4a4080af       JP  ...       0      0            1
1     68NZJ2NODJYM  c24ec4a4080af       JP  ...       0      0            0
2     68NZJ2NODJYM  c24ec4a4080af       JP  ...       0      0            0
3     68NZJ2NODJYM  c24ec4a4080af       JP  ...       0      0            0
4     68NZJ2NODJYM  c24ec4a4080af       JP  ...       0      0            0
...            ...            ...      ...  ...     ...    ...          ...
3654  6ACJKSK689PX  ad343b64b61b3       JP  ...       0      0            0
3655  6ACJKSK689PX  ad343b64b61b3       JP  ...       0      0            0
3656  6ACJKSK689PX  ad343b64b61b3       JP  ...       0      0            0
3657  6ACJKSK689PX  ad343b64b61b3       JP  ...       0      0            0
3658  6ACJKSK689PX  ad343b64b61b3       JP  ...       0      0            0

[3659 rows x 13 columns]

In [133]:
df_t_0

           user_id  ... interaction_counter_vs_impression_counter_max_before
0     68NZJ2NODJYM  ...                                                 20
1     68NZJ2NODJYM  ...                                                100
2     68NZJ2NODJYM  ...                                                  1
3     68NZJ2NODJYM  ...                                                  1
4     68NZJ2NODJYM  ...                                                  1
...            ...  ...                                                ...
3654  6ACJKSK689PX  ...                                                 89
3655  6ACJKSK689PX  ...                                                 73
3656  6ACJKSK689PX  ...                                                 84
3657  6ACJKSK689PX  ...                                                 87
3658  6ACJKSK689PX  ...                                                 87

[3659 rows x 267 columns]

In [134]:
import h5sparse

In [136]:
mat = h5sparse.File("data/proc/vectorizer_1/Xcsr.h5", mode="r")

In [143]:
mat['matrix'][1:3]

<2x2690 sparse matrix of type '<class 'numpy.float32'>'
	with 957 stored elements in Compressed Sparse Row format>

In [148]:
mat.attrs.keys()

In [153]:
mat.ref

In [174]:
mat.keys()

In [176]:
meta = pd.read_hdf("data/proc/vectorizer_1/meta.h5", key="data")

[2020-07-08 14:28:06,690] {utils.py:129} INFO - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2020-07-08 14:28:06,692] {utils.py:141} INFO - NumExpr defaulting to 8 threads.

In [177]:
meta

           user_id     session_id platform  ... is_test is_val  was_clicked
0     68NZJ2NODJYM  c24ec4a4080af       JP  ...       0      0            1
1     68NZJ2NODJYM  c24ec4a4080af       JP  ...       0      0            0
2     68NZJ2NODJYM  c24ec4a4080af       JP  ...       0      0            0
3     68NZJ2NODJYM  c24ec4a4080af       JP  ...       0      0            0
4     68NZJ2NODJYM  c24ec4a4080af       JP  ...       0      0            0
...            ...            ...      ...  ...     ...    ...          ...
2693  0Z4IB9MP6ZFX  7717feba41db7       DE  ...       1      0            0
2694  0Z4IB9MP6ZFX  7717feba41db7       DE  ...       1      0            0
2695  0Z4IB9MP6ZFX  7717feba41db7       DE  ...       1      0            0
2696  0Z4IB9MP6ZFX  7717feba41db7       DE  ...       1      0            0
2697  0Z4IB9MP6ZFX  7717feba41db7       DE  ...       1      0            0

[109744 rows x 13 columns]

# vectorizer

In [11]:
df_18 = pd.read_csv("data/proc/raw_csv/01_train_0018.csv")

In [15]:
vectorizer = make_vectorizer_1()

In [16]:
vectorizer.fit(df_18)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/josang-yeon/2020/tobigs/data/item_metadata_map.joblib'

In [12]:
df_18

,user_id,session_id,timestamp,step,reference,platform,city,device,current_filters,src,...,impression_counter_mean_before_vs_item,clickout_counter_vs_impression_counter_max_after,clickout_counter_vs_impression_counter_max_before,identifier_counter_rank_norm_after,impression_counter_rank_norm,impression_counter_mean_prev_3_vs_item,clickout_counter_vs_interaction_counter_pure,impression_counter_min_before_vs_item,top_7_impression_counter_mean_first_3_vs_item,interaction_counter_vs_impression_counter_max_before
0,UJ5JHT0ZOO6F,4d9e5c162e8ae,1541039082,3,6833196,MY,"Seoul, South Korea",desktop,NaN,train,...,100,288,0,66,100,100,100000000,31,10000,1
1,UJ5JHT0ZOO6F,4d9e5c162e8ae,1541039082,3,6833196,MY,"Seoul, South Korea",desktop,NaN,train,...,100,98,0,8922,8000,6716,50375000,2513,100,100
2,UJ5JHT0ZOO6F,4d9e5c162e8ae,1541039082,3,6833196,MY,"Seoul, South Korea",desktop,NaN,train,...,0,10000,0,66,100,66,66916668,31,10000,1
3,UJ5JHT0ZOO6F,4d9e5c162e8ae,1541039082,3,6833196,MY,"Seoul, South Korea",desktop,NaN,train,...,10000,10000,0,10000,1282,10000,50187500,402,100,16
4,UJ5JHT0ZOO6F,4d9e5c162e8ae,1541039082,3,6833196,MY,"Seoul, South Korea",desktop,NaN,train,...,10000,10000,0,10000,526,10000,40150000,165,10000,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3802,O0XFE529NGU6,b82d6bcce1e31,1541688700,3,4773978,JP,"Seoul, South Korea",mobile,Excellent Rating,test,...,100,19880,1,1168,111,1129,304195,92,800,90
3803,O0XFE529NGU6,b82d6bcce1e31,1541688700,3,4773978,JP,"Seoul, South Korea",mobile,Excellent Rating,test,...,4,292,85,53,112,55,309977,93,200,91
3804,O0XFE529NGU6,b82d6bcce1e31,1541688700,3,4773978,JP,"Seoul, South Korea",mobile,Excellent Rating,test,...,5,82,195,62,134,75,312317,110,32,108
3805,O0XFE529NGU6,b82d6bcce1e31,1541688700,3,4773978,JP,"Seoul, South Korea",mobile,Excellent Rating,test,...,7,78,195,87,145,103,310166,119,23,117
3806,O0XFE529NGU6,b82d6bcce1e31,1541688700,3,4773978,JP,"Seoul, South Korea",mobile,Excellent Rating,test,...,56,100,195,49,130,81,316328,107,74,105

In [164]:
df_es.user_id.value_counts()

ID0D6NEZ5BAU    1000
79T91I97FO1Z     521
AEYKDH92W5LO     478
0M7PD3QOH1JB     452
OGAG0QIHN6GN     445
                ...
1ISM0MHVY14K       1
54JM33E7233N       1
M1L4OOH73PO6       1
7ED67LPDFP90       1
8Y0F7BIJKG4E       1
Name: user_id, Length: 2008, dtype: int64

            user_id     session_id   timestamp  ...  clickout_max_step          dt is_val
16283  79T91I97FO1Z  85c47768c1ddf  1541322665  ...                  1  2018-11-04      0
16302  79T91I97FO1Z  85c47768c1ddf  1541322748  ...                  4  2018-11-04      0
16303  79T91I97FO1Z  85c47768c1ddf  1541322751  ...                  4  2018-11-04      0
16304  79T91I97FO1Z  85c47768c1ddf  1541322751  ...                  2  2018-11-04      0
16305  79T91I97FO1Z  85c47768c1ddf  1541322790  ...                  4  2018-11-04      0
...             ...            ...         ...  ...                ...         ...    ...
33593  79T91I97FO1Z  cd379dd6a7ff8  1541548080  ...                  2  2018-11-06      0
33594  79T91I97FO1Z  cd379dd6a7ff8  1541548082  ...                  2  2018-11-06      0
33595  79T91I97FO1Z  cd379dd6a7ff8  1541548082  ...                  1  2018-11-06      0
33598  79T91I97FO1Z  cd379dd6a7ff8  1541548173  ...                  2  2018-11-06      0
33600  79T91I97FO1Z  cd379dd6a7ff8  1541548347  ...                  2  2018-11-06      1

[521 rows x 21 columns]

In [168]:
df_es[df_es.user_id == "79T91I97FO1Z"].groupby(["action_type","session_id"]).max()

                                        timestamp  step  ...  clickout_max_step  is_val
action_type             session_id                       ...
change of sort order    85c47768c1ddf  1541323261     7  ...                  4       0
                        cd379dd6a7ff8  1541548082     2  ...                  2       0
clickout item           85c47768c1ddf  1541327378   476  ...                  4       0
                        cd379dd6a7ff8  1541548347     5  ...                  2       1
filter selection        85c47768c1ddf  1541323261     8  ...                  2       0
                        cd379dd6a7ff8  1541548082     3  ...                  1       0
interaction item deals  85c47768c1ddf  1541325531   159  ...                  1       0
interaction item image  85c47768c1ddf  1541327548   515  ...                459       0
interaction item info   85c47768c1ddf  1541326970   444  ...                 18       0
interaction item rating 85c47768c1ddf  1541327548   516  ...                 27       0
search for destination  85c47768c1ddf  1541322665     1  ...                  1       0

[11 rows x 7 columns]

In [169]:
df_es[df_es.user_id == "79T91I97FO1Z"].groupby(["action_type","session_id"]).rank()

       timestamp  step  is_test  ...  clickout_step  clickout_max_step  is_val
16283        1.0   1.0      1.0  ...            1.0                1.0     1.0
16302        1.0   1.0      2.5  ...            1.0                2.5     2.5
16303        2.0   2.0      2.5  ...            2.0                2.5     2.5
16304        1.0   1.0      1.5  ...            1.0                1.5     1.5
16305        1.0   1.0      2.5  ...            1.0                2.5     2.5
...          ...   ...      ...  ...            ...                ...     ...
33593        1.0   1.0      1.5  ...            1.0                1.5     1.5
33594        2.0   2.0      1.5  ...            2.0                1.5     1.5
33595        1.0   1.0      1.0  ...            1.0                1.0     1.0
33598        1.0   1.0      1.5  ...            1.0                1.5     1.0
33600        2.0   2.0      1.5  ...            2.0                1.5     2.0

[521 rows x 7 columns]

In [170]:
df_es[df_es.user_id == "79T91I97FO1Z"]

            user_id     session_id   timestamp  ...  clickout_max_step          dt is_val
16283  79T91I97FO1Z  85c47768c1ddf  1541322665  ...                  1  2018-11-04      0
16302  79T91I97FO1Z  85c47768c1ddf  1541322748  ...                  4  2018-11-04      0
16303  79T91I97FO1Z  85c47768c1ddf  1541322751  ...                  4  2018-11-04      0
16304  79T91I97FO1Z  85c47768c1ddf  1541322751  ...                  2  2018-11-04      0
16305  79T91I97FO1Z  85c47768c1ddf  1541322790  ...                  4  2018-11-04      0
...             ...            ...         ...  ...                ...         ...    ...
33593  79T91I97FO1Z  cd379dd6a7ff8  1541548080  ...                  2  2018-11-06      0
33594  79T91I97FO1Z  cd379dd6a7ff8  1541548082  ...                  2  2018-11-06      0
33595  79T91I97FO1Z  cd379dd6a7ff8  1541548082  ...                  1  2018-11-06      0
33598  79T91I97FO1Z  cd379dd6a7ff8  1541548173  ...                  2  2018-11-06      0
33600  79T91I97FO1Z  cd379dd6a7ff8  1541548347  ...                  2  2018-11-06      1

[521 rows x 21 columns]

In [162]:
df_es

            user_id     session_id   timestamp  ...  clickout_max_step          dt is_val
0      6B86JDD3UW7A  447ef5a11b6fc  1541030611  ...                  1  2018-11-01      0
1      6B86JDD3UW7A  447ef5a11b6fc  1541030675  ...                  1  2018-11-01      0
2      6B86JDD3UW7A  447ef5a11b6fc  1541030775  ...                  1  2018-11-01      0
3      LAYU76NFE98T  61208de881b0e  1541030959  ...                  2  2018-11-01      0
4      LAYU76NFE98T  61208de881b0e  1541030959  ...                  2  2018-11-01      0
...             ...            ...         ...  ...                ...         ...    ...
39929  0Z4IB9MP6ZFX  7717feba41db7  1541719852  ...                  1  2018-11-08      0
39930  0Z4IB9MP6ZFX  7717feba41db7  1541719862  ...                  1  2018-11-08      0
39931  0Z4IB9MP6ZFX  7717feba41db7  1541719871  ...                  1  2018-11-08      0
39932  XHK8346FKDN9  afb0ecf8b6773  1541720331  ...                  1  2018-11-08      0
39933  M9KCCP0T97FW  9356a7ae1f553  1541721077  ...                  1  2018-11-08      0

[39934 rows x 21 columns]